
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

import datetime
import threading
import speech_recognition as sr
import pyaudio as ptg
from imports.auth import * # * --> all
import openai
import pyttsx3
import sqlite3
from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

openai.api_key=api_key
r=sr.Recognizer()
OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\ajenj\Documents\GitHub\ChatAlexa\ChatGPT-Alexa\assets\frame0")

boton_close=False
def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


############################## CENTINELA DE INICIO
def antes_chatear():
    global boton_close
    if boton_close==True:
        boton_close=False
    else:
        print("hola")
        boton_close=True
        threading.Thread(target=chatear).start()
        print("hola2")
def chatear():
    global boton_close
    conversation=""
    engine=pyttsx3.init()
    engine.setProperty('voice',0)
    engine.setProperty('rate',150)

    miConexion=sqlite3.connect("chat.bd")
    miCursor=miConexion.cursor()
    try:
        miCursor.execute("CREATE TABLE HISTORIAL(ID INTEGER PRIMARY KEY AUTOINCREMENT, PREGUNTA TEXT, RESPUESTA TEXT, FECHA DATETIME)")
    except:
        pass
        while(boton_close):
            with sr.Microphone() as source:
                r.adjust_for_ambient_noise(source,duration=2)
                if boton_close==False:
                    break
                print("Escuchando...")
                if boton_close==False:
                    break
                audio=r.listen(source)
            try:
                text=str(r.recognize_google(audio,language=language_chat))
                conversation+="\Humano: "+text+"\nAI: "
                conversation=conversation.strip()
                response=openai.Completion.create(engine="text-davinci-003",prompt=conversation,temperature=0.9,max_tokens=150,top_p=1,frequency_penalty=0,presence_penalty=0.6, stop=["\n","Humano","AI"])
                if boton_close==False:
                    break
                answer=response.choices[0].text
                conversation+=answer
                fecha=datetime.datetime.fromtimestamp(response.created).strftime('%H:%M:%S')
                print(f"AI ({fecha}): {answer}\n")
                engine.say(answer)
                engine.runAndWait()
                
                miCursor.execute("INSERT INTO HISTORIAL (PREGUNTA, RESPUESTA, FECHA) VALUES(?, ?, ?)",(text,answer,datetime.datetime.fromtimestamp(response.created)))
            
            except:
                print("No reconozco tu voz")
        
        miConexion.commit()
        miConexion.close()
        engine.say("Hasta pronto!")
        engine.runAndWait()
        
        print("\nHasta pronto!")
window = Tk()

window.geometry("745x501")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 501,
    width = 745,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    189.0,
    34.0,
    anchor="nw",
    text="Bienvenido",
    fill="#000000",
    font=("Inter Bold", 24 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    373.0,
    176.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#F9F9F9",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=197.0,
    y=128.0,
    width=352.0,
    height=95.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    395.0,
    367.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#F9F9F9",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=219.0,
    y=317.0,
    width=352.0,
    height=98.0
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    115.0,
    176.0,
    image=image_image_1
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=antes_chatear,
    relief="flat"
)
button_1.place(
    x=595.0,
    y=309.0,
    width=108.0,
    height=108.0
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    649.0,
    363.0,
    image=image_image_2
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    relief="flat"
)
button_2.place(
    x=649.0,
    y=29.0,
    width=48.0,
    height=48.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=661.0,
    y=41.0,
    width=24.0,
    height=24.0
)

canvas.create_text(
    230.0,
    454.0,
    anchor="nw",
    text="Actualización 2023",
    fill="#000000",
    font=("Inter Light", 12 * -1)
)
window.resizable(False, False)
window.mainloop()
